language: python
dist: xenial
sudo: false
python:	
  - "2.7"	
  - "3.5"	
  - "3.6"	
  - "3.7"

env:
  - TRAVIS_PYLINT=false

matrix:
  include:
    - os: windows
      language: sh
      python: 3.7
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
      install: skip
      script: python -m pip install .[testing,doc] && pytest --cov=slash --cov-report=html tests
    - os: linux
      dist: xenial
      python: "3.6"
      env: TRAVIS_PYLINT=true

# command to run tests, e.g. python setup.py test
install: 
  - pip install virtualenv
  - pip install codecov
script: 
  - if [[ "$TRAVIS_OS_NAME" == 'windows' ]]; then python -m pip install .[testing,doc]; else make env; fi
  - if [[ $TRAVIS_PYLINT == 'true' ]]; then make pylint; elif [[ "$TRAVIS_OS_NAME" == 'windows' ]];  then pytest --cov=slash --cov-report=html tests; else make test; fi
after_success:
  - codecov
after_failure:
- .env/bin/pip freeze

deploy:
  - provider: pypi
    user: vmalloc
    password:
      secure: EBE30QsQvwodsakJRtXvmeah0KRQoMpHQSfSACjE0FviWU6eHhgE7nSzxrTSwetmLaB/+hexkys8ULsE4Dxwgvd8aXJ5T6+GnhFkWLgaTl8Q39g/cnLqnVj+OCS95XlyFcWyBLsdyPY+tAc34YpYRfjuWgXup5UNc7Ze2KQ7wqk=
    on:
      tags: true
      repo: getslash/slash
      python: "3.6"
      condition: $TRAVIS_PYLINT = 'false'
